// Free-tier job scanning agent.
//
// Runs on a schedule via .github/workflows/job-scan.yml (GitHub Actions cron,
// free/unlimited on this public repo). Pulls from two sources:
//   1. Adzuna + JSearch (RapidAPI) — general aggregators for "Product Manager"
//      roles in India.
//   2. Direct ATS APIs (Greenhouse, Lever, Ashby, SmartRecruiters, Workable)
//      for the specific companies listed in agent/companies.json — this is
//      the same technique TrueUp uses for its core job data: these APIs are
//      public and unauthenticated *because companies deliberately expose them
//      to be embedded/aggregated elsewhere*, unlike LinkedIn/Naukri, which
//      explicitly prohibit this and which we hit 403s against ourselves this
//      session. Every endpoint below was verified live against a real company
//      before being wired in, not guessed from docs.
//   3. Indian government / PSU / govt-backed sources with structured data
//      (see govt.mjs + govt-sources.json): NPCI and subsidiaries, RBIH, DIC's
//      recruitment portal, CSC, NHAI, Bharat Digital. Looser title filter,
//      since govt orgs rarely title roles "Product Manager".
//
// Diffs against what it saw last run (agent/seen-jobs.json, committed back to
// the repo by the workflow), and pings Telegram only with what's new.
//
// Deliberately does NOT touch Naukri, IIMJobs, Hirist, Foundit, or Shine —
// no legal API exists for those. Those stay covered by the app's own
// link-launcher + "last checked" tracking instead of scraping.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sendAlert } from './notify.mjs';
import { fetchGovtOpenings, mapLimited } from './govt.mjs';
import { updateAtsSignals, saveSignals } from './signals.mjs';
import { fetchFundingSignals } from './funding.mjs';
import { fetchVcBoards } from './vc-boards.mjs';
import { fetchEightfold, fetchOracle, fetchSuccessFactors, fetchAmazon } from './enterprise-ats.mjs';
import { fetchYcJobs, indiaEligibility } from './yc.mjs';
import { saveRoleSnapshot, isAiTitle, roleLevel } from './snapshots.mjs';
import { istToday, loadQueue, saveQueue, enqueue, urgentItems, urgentText, digestText, markReminders } from './digest.mjs';

const AGENT_DIR = path.dirname(fileURLToPath(import.meta.url));
const SEEN_FILE = path.join(AGENT_DIR, 'seen-jobs.json');
const COMPANIES_FILE = path.join(AGENT_DIR, 'companies.json');
// Current govt PM openings, read by the app's Govt & PSU tab straight from GitHub.
const GOVT_OPENINGS_FILE = path.join(AGENT_DIR, 'govt-openings.json');
// The Companies tab's directory (MNCs, IT majors, unicorns): generated by
// scripts/build-company-directory.mjs; only companies with a readable job feed.
const DIRECTORY_FILE = path.join(AGENT_DIR, 'directory-companies.json');
// Open PM roles in India per company, read live by the app's Companies tab.
const COMPANY_ROLES_FILE = path.join(AGENT_DIR, 'company-roles.json');
const YC_ROLES_FILE = path.join(AGENT_DIR, 'yc-roles.json');
const AI_ROLES_FILE = path.join(AGENT_DIR, 'ai-roles.json');
const INDIA_RE = /india|bengaluru|bangalore|mumbai|delhi|gurgaon|gurugram|noida|hyderabad|pune|chennai|kolkata|ahmedabad|jaipur|kochi|chandigarh|indore|coimbatore|\bncr\b/i;
const env = (name) => process.env[name];

// Broad enough to catch "Product Manager", "Senior Product Manager", "Group
// Product Manager", "Product Owner", "Head/Director/VP of Product" — company
// ATS feeds return every open role, not just PM ones, so this filters them
// down before anything reaches Telegram. Adjust to taste.
// "Product Management - UPI" (Paytm's titling) and "Product Lead" are PM roles too.
const PM_TITLE_REGEX = /product\s*(manager|owner|management\b|lead\b)|head\s+of\s+product|director.{0,15}product|vp.{0,15}product|group\s*product\s*manager/i;

async function fetchAdzuna() {
  const appId = env('ADZUNA_APP_ID');
  const appKey = env('ADZUNA_APP_KEY');
  if (!appId || !appKey) {
    console.log('Adzuna: skipped (ADZUNA_APP_ID / ADZUNA_APP_KEY not set)');
    return [];
  }
  try {
    const url = `https://api.adzuna.com/v1/api/jobs/in/search/1?app_id=${appId}&app_key=${appKey}&results_per_page=30&what=product%20manager&content-type=application/json`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    return (data.results || []).map(j => ({
      id: `adzuna-${j.id}`,
      title: j.title,
      company: j.company?.display_name || 'Unknown',
      location: j.location?.display_name || '',
      url: j.redirect_url,
      source: 'Adzuna',
    }));
  } catch (err) {
    console.error('Adzuna fetch failed:', err.message);
    return [];
  }
}

async function fetchJSearch() {
  const key = env('RAPIDAPI_KEY');
  if (!key) {
    console.log('JSearch: skipped (RAPIDAPI_KEY not set)');
    return [];
  }
  try {
    const url = 'https://jsearch.p.rapidapi.com/search?query=' + encodeURIComponent('Product Manager in India') + '&page=1&num_pages=1&date_posted=today';
    const res = await fetch(url, {
      headers: { 'X-RapidAPI-Key': key, 'X-RapidAPI-Host': 'jsearch.p.rapidapi.com' },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    return (data.data || []).map(j => ({
      id: `jsearch-${j.job_id}`,
      title: j.job_title,
      company: j.employer_name || 'Unknown',
      location: [j.job_city, j.job_country].filter(Boolean).join(', '),
      url: j.job_apply_link,
      source: 'JSearch (' + (j.job_publisher || 'aggregated') + ')',
    }));
  } catch (err) {
    console.error('JSearch fetch failed:', err.message);
    return [];
  }
}

// Your companies.json plus the Companies-tab directory. Directory entries are
// India-only (global MNC boards list PM roles everywhere) and yours win on a
// name clash, so your own settings for a company are never overridden.
async function loadCompanies() {
  const read = async (file, label) => {
    try {
      return JSON.parse(await fs.readFile(file, 'utf8'));
    } catch (err) {
      console.log(`${label}: none found or unreadable —`, err.message);
      return [];
    }
  };
  const mine = await read(COMPANIES_FILE, 'companies.json');
  const directory = (await read(DIRECTORY_FILE, 'directory-companies.json')).map(c => ({ ...c, indiaOnly: true, fromDirectory: true }));
  const names = new Set(mine.map(c => c.name.toLowerCase()));
  return [...mine, ...directory.filter(c => !names.has(c.name.toLowerCase()))];
}

// Verified live: GET https://boards-api.greenhouse.io/v1/boards/{slug}/jobs
// -> { jobs: [{ id, title, location:{name}, updated_at, absolute_url }] }
async function fetchGreenhouse(company) {
  const res = await fetch(`https://boards-api.greenhouse.io/v1/boards/${company.slug}/jobs`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (data.jobs || []).map(j => ({
    id: `greenhouse-${company.slug}-${j.id}`,
    title: j.title,
    company: company.name,
    location: j.location?.name || '',
    url: j.absolute_url,
    source: `Greenhouse (${company.name})`,
  }));
}

// Verified live: GET https://api.lever.co/v0/postings/{slug}?mode=json
// -> [{ id, text, categories:{location}, createdAt, hostedUrl }]
async function fetchLever(company) {
  const res = await fetch(`https://api.lever.co/v0/postings/${company.slug}?mode=json`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  if (!Array.isArray(data)) return []; // Lever returns {"ok":false,...} for an unknown slug
  return data.map(j => ({
    id: `lever-${company.slug}-${j.id}`,
    title: j.text,
    company: company.name,
    location: j.categories?.location || '',
    url: j.hostedUrl,
    source: `Lever (${company.name})`,
  }));
}

// Verified live: GET https://api.ashbyhq.com/posting-api/job-board/{slug}
// -> { jobs: [{ id, title, location, publishedAt, jobUrl }] }
async function fetchAshby(company) {
  const res = await fetch(`https://api.ashbyhq.com/posting-api/job-board/${company.slug}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (data.jobs || []).map(j => ({
    id: `ashby-${company.slug}-${j.id}`,
    title: j.title,
    company: company.name,
    location: j.location || '',
    url: j.jobUrl || j.applyUrl,
    source: `Ashby (${company.name})`,
  }));
}

// Verified live: GET https://api.smartrecruiters.com/v1/companies/{slug}/postings
// -> { content: [{ id, name, location:{fullLocation}, company:{identifier} }] }
// No URL field in the list response — the public posting URL is constructed
// as jobs.smartrecruiters.com/{identifier}/{id}, confirmed live (200).
async function fetchSmartRecruiters(company) {
  const res = await fetch(`https://api.smartrecruiters.com/v1/companies/${company.slug}/postings`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (data.content || []).map(j => ({
    id: `smartrecruiters-${company.slug}-${j.id}`,
    title: j.name,
    company: company.name,
    location: j.location?.fullLocation || '',
    url: `https://jobs.smartrecruiters.com/${j.company?.identifier || company.slug}/${j.id}`,
    source: `SmartRecruiters (${company.name})`,
  }));
}

// Verified live: GET https://apply.workable.com/api/v1/widget/accounts/{slug}
// -> { jobs: [{ title, url, application_url, city, country, created_at }] }
async function fetchWorkable(company) {
  const res = await fetch(`https://apply.workable.com/api/v1/widget/accounts/${company.slug}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (data.jobs || []).map(j => ({
    id: `workable-${company.slug}-${j.shortcode || j.code}`,
    title: j.title,
    company: company.name,
    location: [j.city, j.country].filter(Boolean).join(', '),
    url: j.url || j.application_url,
    source: `Workable (${company.name})`,
  }));
}

// Verified live: GET https://{slug}.recruitee.com/api/offers/
// -> { offers: [{ id, title, location, careers_apply_url }] }
async function fetchRecruitee(company) {
  const res = await fetch(`https://${company.slug}.recruitee.com/api/offers/`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (data.offers || []).map(j => ({
    id: `recruitee-${company.slug}-${j.id}`,
    title: j.title,
    company: company.name,
    location: j.location || '',
    url: j.careers_apply_url,
    source: `Recruitee (${company.name})`,
  }));
}

// ─── Indian ATS platforms (most Indian startups use these, not Greenhouse) ───
// All verified live 2026-09-27.

// Zoho Recruit: GET https://{slug}.zohorecruit.{in|com}/recruit/v2/public/Job_Openings?pagename=Careers&source=CareerSite
// -> { data: [{ id, Posting_Title, City, Country, $url }] }. `domain` defaults to .in.
async function fetchZoho(company) {
  const res = await fetch(`https://${company.slug}.zohorecruit.${company.domain || 'in'}/recruit/v2/public/Job_Openings?pagename=Careers&source=CareerSite`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (data.data || []).map(j => ({
    id: `zoho-${company.slug}-${j.id}`,
    title: j.Posting_Title,
    company: company.name,
    location: [j.City, j.Country].filter(Boolean).join(', '),
    url: j['$url'],
    source: `Zoho Recruit (${company.name})`,
  }));
}

// Keka: GET https://{slug}.keka.com/careers/api/jobs/default/active
// -> [{ id, title, jobLocations:[{ city, countryName }], publishedOn }]
async function fetchKeka(company) {
  const res = await fetch(`https://${company.slug}.keka.com/careers/api/jobs/default/active`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (Array.isArray(data) ? data : []).map(j => ({
    id: `keka-${company.slug}-${j.id}`,
    title: j.title,
    company: company.name,
    location: (j.jobLocations || []).map(l => l.city || l.countryName).filter(Boolean).join(', '),
    url: `https://${company.slug}.keka.com/careers/jobdetails/${j.id}`,
    source: `Keka (${company.name})`,
  }));
}

// Freshteam: GET https://{slug}.freshteam.com/hire/widgets/jobs.json
// -> { jobs: [{ id, title, url, branch_id, status, deleted }], branches: [{ id, location }] }
async function fetchFreshteam(company) {
  const res = await fetch(`https://${company.slug}.freshteam.com/hire/widgets/jobs.json`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  const branches = new Map((data.branches || []).map(b => [b.id, b.location]));
  return (data.jobs || []).filter(j => j.status === 2 && !j.deleted).map(j => ({
    id: `freshteam-${company.slug}-${j.id}`,
    title: (j.title || '').trim(),
    company: company.name,
    location: branches.get(j.branch_id) || (j.remote ? 'Remote' : ''),
    url: j.url,
    source: `Freshteam (${company.name})`,
  }));
}

// ─── Workday (large enterprises, GCCs, big tech) ─────────────────────────────
// Verified live 2026-09-30: POST https://{tenant}.wd{N}.myworkdayjobs.com/wday/cxs/{tenant}/{site}/jobs
// -> { total, jobPostings: [{ title, externalPath, locationsText, postedOn }] }
// Workday's search is fuzzy ("product manager" matches ~every job at a big
// company), so the query adds "India" (which matches the location) and titles
// are filtered afterwards. slug: { tenant, wd, site }, plus host for tenants on
// the shared myworkdaysite.com domain (Wells Fargo: wd1.myworkdaysite.com).
async function fetchWorkday(company) {
  const { tenant, wd, site, host } = company.slug;
  const base = `https://${host || `${tenant}.wd${wd}.myworkdayjobs.com`}`;
  const publicBase = host ? `${base}/recruiting/${tenant}/${site}` : `${base}/${site}`;
  const jobs = [];
  let total = 0; // Workday only reports the total on the first page (later pages say 0)
  for (let offset = 0; offset < 200; offset += 20) {
    const res = await fetch(`${base}/wday/cxs/${tenant}/${site}/jobs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({ appliedFacets: {}, limit: 20, offset, searchText: 'product manager India' }),
      signal: AbortSignal.timeout(30000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    const page = data.jobPostings || [];
    if (offset === 0) total = data.total ?? 0;
    jobs.push(...page);
    if (page.length < 20 || jobs.length >= total) break;
  }
  return jobs.map(j => ({
    id: `workday-${tenant}-${j.externalPath}`,
    title: j.title,
    company: company.name,
    location: j.locationsText || '',
    url: `${publicBase}${j.externalPath}`,
    source: `Workday (${company.name})`,
  }));
}

// Rippling ATS: GET https://api.rippling.com/platform/api/ats/v1/board/{slug}/jobs
// -> [{ uuid, name, url, workLocation: { label } }]. Verified live 2026-10-05.
async function fetchRippling(company) {
  const res = await fetch(`https://api.rippling.com/platform/api/ats/v1/board/${company.slug}/jobs`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return (Array.isArray(data) ? data : []).map(j => ({
    id: `rippling-${company.slug}-${j.uuid}`,
    title: j.name,
    company: company.name,
    location: j.workLocation?.label || '',
    url: j.url,
    source: `Rippling (${company.name})`,
  }));
}

const ATS_FETCHERS = {
  greenhouse: fetchGreenhouse,
  lever: fetchLever,
  ashby: fetchAshby,
  smartrecruiters: fetchSmartRecruiters,
  workable: fetchWorkable,
  recruitee: fetchRecruitee,
  zoho: fetchZoho,
  keka: fetchKeka,
  freshteam: fetchFreshteam,
  workday: fetchWorkday,
  eightfold: fetchEightfold,
  oracle: fetchOracle,
  successfactors: fetchSuccessFactors,
  amazon: fetchAmazon,
  rippling: fetchRippling,
};

// Returns { pmJobs, boards }: the PM postings, plus every company board read
// successfully this run (all roles), which the hiring-signal checks use.
async function fetchCompanyATS() {
  const companies = await loadCompanies();
  if (companies.length === 0) return { pmJobs: [], boards: [] };
  const boards = [];

  const results = await mapLimited(companies, 8, async (company) => {
    const fetcher = ATS_FETCHERS[company.ats];
    if (!fetcher) {
      console.error(`${company.name}: unknown ats "${company.ats}" — must be one of ${Object.keys(ATS_FETCHERS).join(', ')}`);
      return [];
    }
    try {
      const jobs = (await fetcher(company)).filter(j => j.title);
      boards.push({ company: company.name, jobs, fromDirectory: !!company.fromDirectory });
      return jobs
        .filter(j => PM_TITLE_REGEX.test(j.title) && (!company.indiaOnly || INDIA_RE.test(j.location || '')))
        .map(j => (company.fromDirectory ? { ...j, baselineKey: `co:${company.name}` } : j));
    } catch (err) {
      console.error(`${company.name} (${company.ats}) fetch failed:`, err.cause?.code || err.message);
      return [];
    }
  });

  return { pmJobs: results.flat(), boards, directoryRead: boards.filter(b => b.fromDirectory).map(b => `co:${b.company}`) };
}

async function loadSeen() {
  try {
    const raw = await fs.readFile(SEEN_FILE, 'utf8');
    return { baselinedOrgs: [], ...JSON.parse(raw) };
  } catch {
    return { ids: [], firstRun: true, baselinedOrgs: [] };
  }
}

async function saveSeen(ids, baselinedOrgs) {
  // Keep the file bounded: the most recent 3000 ids (govt careers pages add a
  // few hundred notice ids on top of the job feeds).
  const trimmed = ids.slice(-3000);
  await fs.writeFile(SEEN_FILE, JSON.stringify({ ids: trimmed, firstRun: false, baselinedOrgs: [...baselinedOrgs].sort() }, null, 2));
}

// Open PM roles in India per company, for the app's Companies tab. A company
// whose board failed this run keeps its last-known roles for up to 7 days.
async function saveCompanyRoles(pmJobs, boards) {
  let previous = { roles: {}, lastRead: {} };
  try { previous = { ...previous, ...JSON.parse(await fs.readFile(COMPANY_ROLES_FILE, 'utf8')) }; } catch { /* first run */ }
  const today = new Date().toISOString().slice(0, 10);
  const weekAgo = new Date(Date.now() - 7 * 86_400_000).toISOString().slice(0, 10);
  const read = new Set(boards.map(b => b.company));
  const roles = {};
  for (const [company, list] of Object.entries(previous.roles)) {
    if (!read.has(company) && (previous.lastRead[company] || '') >= weekAgo) roles[company] = list.map(r => ({ ...r, level: r.level || roleLevel(r.title) }));
  }
  const firstSeen = new Map(Object.values(previous.roles).flat().map(r => [r.id, r.firstSeen]));
  for (const j of pmJobs.filter(j => INDIA_RE.test(j.location || ''))) {
    (roles[j.company] ||= []).push({ id: j.id, title: j.title, location: j.location, url: j.url, level: roleLevel(j.title), firstSeen: firstSeen.get(j.id) || today });
  }
  const lastRead = { ...previous.lastRead };
  for (const c of read) lastRead[c] = today;
  const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
  for (const list of Object.values(roles)) list.sort((a, b) => a.title.localeCompare(b.title));
  await fs.writeFile(COMPANY_ROLES_FILE, JSON.stringify({ scannedAt: new Date().toISOString(), roles: sorted(roles), lastRead: sorted(lastRead) }, null, 2) + '\n');
}

// Writes the current govt openings for the app. A source that failed this run
// keeps its last-known openings rather than vanishing from the app; firstSeen
// is carried over so the app can badge what's new. lastRead records, per org,
// the last day the scanner could read it, so the app can say which orgs are
// covered automatically and which (geo-blocked, JS-only) need a manual check.
async function saveGovtOpenings({ jobs, failed, readOk }) {
  let previous = { openings: [], lastRead: {} };
  try {
    previous = { ...previous, ...JSON.parse(await fs.readFile(GOVT_OPENINGS_FILE, 'utf8')) };
  } catch { /* first run */ }
  const firstSeenById = new Map(previous.openings.map(o => [o.id, o.firstSeen]));
  const today = new Date().toISOString().slice(0, 10);
  // Carry-over is for a flaky day, not forever: once an org hasn't been read
  // for 7 days its old openings drop out (the app then marks it "Check manually").
  const weekAgo = new Date(Date.now() - 7 * 86_400_000).toISOString().slice(0, 10);
  const kept = previous.openings.filter(o => failed.includes(o.org) && (previous.lastRead[o.org] || '') >= weekAgo);
  const openings = [...jobs.map(j => ({ ...j, firstSeen: firstSeenById.get(j.id) || today })), ...kept]
    .sort((a, b) => (b.firstSeen || '').localeCompare(a.firstSeen || '') || a.id.localeCompare(b.id));
  const lastRead = { ...previous.lastRead };
  for (const org of readOk) lastRead[org] = today;
  const sortedLastRead = Object.fromEntries(Object.entries(lastRead).sort(([a], [b]) => a.localeCompare(b)));
  await fs.writeFile(GOVT_OPENINGS_FILE, JSON.stringify({ openings, lastRead: sortedLastRead }, null, 2) + '\n');
  return jobs;
}

async function main() {
  const isPm = (title) => PM_TITLE_REGEX.test(title);
  const [adzuna, jsearch, atsResult, govtResult, vcResult, fundingSignals, ycResult] = await Promise.all([
    fetchAdzuna(), fetchJSearch(), fetchCompanyATS(), fetchGovtOpenings(), fetchVcBoards(isPm), fetchFundingSignals(), fetchYcJobs(isPm),
  ]);
  const yc = ycResult.jobs;
  if (ycResult.ok) await saveRoleSnapshot(YC_ROLES_FILE, yc);
  const vc = vcResult.jobs;
  const companyATS = atsResult.pmJobs;
  await saveCompanyRoles(companyATS, atsResult.boards);
  const govt = await saveGovtOpenings(govtResult);
  const today = new Date().toISOString().slice(0, 10);
  // Funding news is shown for every raise in the app, but only raises at companies in
  // companies.json make it into the phone alert.
  const watched = new Set((await loadCompanies()).map(c => c.name.toLowerCase()));
  const atsSignals = [...await updateAtsSignals(atsResult.boards, isPm, today), ...fundingSignals.map(s => ({ ...s, ...(watched.has(s.company.toLowerCase()) && { watched: true }) }))];
  const freshSignals = await saveSignals(atsSignals, today);
  if (atsSignals.length) console.log(`Hiring signals: ${atsSignals.length} (${atsSignals.filter(s => s.type !== 'funding').map(s => `${s.type} @ ${s.company}`).join(', ') || 'funding news only'})`);
  const allJobs = [...adzuna, ...jsearch, ...companyATS, ...govt, ...vc, ...yc];
  console.log(`Fetched ${adzuna.length} from Adzuna, ${jsearch.length} from JSearch, ${companyATS.length} from company ATS feeds, ${govt.length} from govt/PSU sources, ${vc.length} from VC portfolio boards, ${yc.length} from YC (${allJobs.length} total).`);

  // AI PM roles: an AI-flavoured title anywhere, or any PM role at an AI-native
  // company; India-based or remote-open-to-India only. Govt roles excluded.
  const aiCompanies = new Set((await loadCompanies()).filter(c => c.sector === 'ai').map(c => c.name.toLowerCase()));
  const aiRoles = [...companyATS, ...vc, ...yc, ...adzuna, ...jsearch]
    .filter(j => indiaEligibility(j.location || '') || /india/i.test(j.source || ''))
    .map(j => (isAiTitle(j.title) ? { ...j, aiMatch: 'title' } : aiCompanies.has((j.company || '').toLowerCase()) ? { ...j, aiMatch: 'company' } : null))
    .filter(Boolean);
  await saveRoleSnapshot(AI_ROLES_FILE, aiRoles);
  console.log(`AI PM roles (India / remote-India): ${aiRoles.length}`);

  const seen = await loadSeen();
  const seenSet = new Set(seen.ids);
  // The first successful read of a govt careers page is a baseline: it can
  // hold every notice currently up, so record those silently and only alert
  // on what appears after. Per org, so a page that was unreachable for
  // weeks doesn't flood the alert the day it comes back.
  // Only a real backlog (4+ matching notices on that first read) is held back;
  // with the notice filter this strict, one or two matches are worth an alert.
  const baselined = new Set(seen.baselinedOrgs);
  const noticeCount = (org) => govt.filter(j => j.org === org && j.id.startsWith('govt-notice-')).length;
  const vcCount = (key) => vc.filter(j => j.baselineKey === key).length;
  const baselineNow = new Set([
    ...govtResult.noticePagesRead.filter(org => !baselined.has(org) && noticeCount(org) > 3),
    ...vcResult.readOk.filter(key => !baselined.has(key) && vcCount(key) > 3),   // VC boards list dozens of PM roles on first read
    ...atsResult.directoryRead.filter(key => !baselined.has(key) && companyATS.filter(j => j.baselineKey === key).length > 3),
    ...(ycResult.ok && !baselined.has('yc') && yc.length > 3 ? ['yc'] : []),
  ]);
  const inBaseline = (j) => (j.id.startsWith('govt-notice-') && baselineNow.has(j.org)) || (j.baselineKey && baselineNow.has(j.baselineKey));
  const newJobs = allJobs.filter(j => j.id && !seenSet.has(j.id) && !inBaseline(j));
  if (baselineNow.size) console.log(`Sources with a backlog on first read (recorded, no alert): ${[...baselineNow].join(', ')}`);

  // Every new job goes into the digest queue and is marked seen: the queue,
  // not the seen list, is what holds it until a digest is delivered.
  let queue = await loadQueue();
  const todayIst = istToday();
  const digestSignals = freshSignals.filter(s => s.type !== 'funding' || s.watched);
  if (seen.firstRun) {
    console.log('First run — recording current jobs as a baseline, not sending an alert for all of them.');
  } else {
    console.log(newJobs.length ? `${newJobs.length} new job(s) since last run, queued for the morning digest.` : 'No new jobs since last run.');
    // Jobs left unseen by older runs that had no alert channel are picked up here too.
    queue = enqueue(queue, newJobs, digestSignals, todayIst);
  }

  // Urgent: can't wait for 8 AM.
  const openings = JSON.parse(await fs.readFile(GOVT_OPENINGS_FILE, 'utf8')).openings || [];
  const urgent = urgentItems({ newJobs: seen.firstRun ? [] : newJobs, openings, signals: freshSignals, reminders: queue.reminders, today: todayIst });
  const urgentMsg = urgentText(urgent, todayIst);
  if (urgentMsg) {
    console.log(`Urgent: ${urgent.newClosing.length} new govt role(s) closing soon, ${urgent.reminders.length} deadline reminder(s), ${urgent.reposted.length} reposted role(s).`);
    if (await sendAlert(urgentMsg)) queue = { ...queue, reminders: markReminders(queue.reminders, urgent.reminders, openings, todayIst) };
    else console.log('Urgent alert not delivered; reminders will retry next run.');
  }
  queue = { ...queue, reminders: markReminders(queue.reminders, [], openings, todayIst) };

  // Morning digest: the 8 AM IST run (or a manual run with send_digest) sets SEND_DIGEST=1.
  if (env('SEND_DIGEST') === '1') {
    const text = digestText(queue, openings, todayIst);
    if (!text) console.log('Digest: nothing new to send.');
    else if (await sendAlert(text)) {
      console.log(`Digest sent: ${queue.jobs.length} job(s), ${queue.signals.length} signal(s).`);
      queue = { ...queue, jobs: [], signals: [] };
    } else {
      console.log(`Digest not delivered; ${queue.jobs.length} job(s) stay queued for the next digest.`);
    }
  } else if (queue.jobs.length) {
    console.log(`Digest queue: ${queue.jobs.length} job(s), ${queue.signals.length} signal(s) waiting for 8:00 AM IST.`);
  }
  await saveQueue(queue);

  // Dedupe — without this, a job that's still listed on a later run (the
  // common case, since postings stay up for weeks) gets re-appended every
  // single run, silently filling the id cap with repeats of the same
  // handful of jobs instead of real history.
  // Every careers page read this run is baselined, including ones with no
  // matching notice yet, so the first real notice on it later does alert.
  await saveSeen([...new Set([...seen.ids, ...allJobs.map(j => j.id)])], new Set([...baselined, ...govtResult.noticePagesRead, ...vcResult.readOk, ...atsResult.directoryRead, ...(ycResult.ok ? ['yc'] : [])]));
}

// Keep the process alive until main() settles. The per-request timeouts
// (AbortSignal.timeout) use unref'd timers, so if every remaining request
// stalls, Node would otherwise exit 0 mid-run, silently, leaving the state files
// half-updated for the commit step. With the loop held open those timeouts
// fire and the stalled requests fail normally; the watchdog is the backstop.
const keepAlive = setInterval(() => {}, 60_000);
const watchdog = setTimeout(() => {
  console.error('Agent run exceeded 15 minutes; aborting without saving.');
  process.exit(1);
}, 15 * 60_000);

main()
  .catch(err => {
    console.error('Agent run failed:', err);
    process.exitCode = 1;
  })
  .finally(() => {
    clearInterval(keepAlive);
    clearTimeout(watchdog);
  });
